---
- include: node_dependencies.yml

# This assumes that the packages are available in an existing Apt repo
- name: Install Vertica packages
  apt: name="{{item}}" state=present
  with_items: "{{vertica_packages}}"

- include: node_users.yml
- include: node_setup.yml

- include: cluster.yml


# A DB must exist before the node can startup.
- include: create_db.yml

- meta: flush_handlers

- name: Start vertica
  service: name=verticad state=started enabled=yes
- name: Start vertica_agent
  service: name=vertica_agent state=started enabled=yes
