---
- include: node_dependencies.yml

- name: Install Vertica
  apt:  deb="{{vertica_package_location}}" state=present
  sudo: true

- include: node_users.yml
- include: node_setup.yml

- include: cluster.yml

- include: create_db.yml

- name: Start vertica
  service: name=verticad state=started enabled=yes
- name: Start vertica_agent
  service: name=vertica_agent state=started enabled=yes
