---
- include: node_dependencies.yml

- name: Install Vertica
  apt:  deb="{{vertica_package_location}}" state=present
  sudo: true

- include: node_users.yml
- include: node_setup.yml

- include: cluster.yml

- name: Delete requirement ntp from init script
  lineinfile: 'dest=/etc/init.d/verticad regexp="# Required-Start: \$network ntpd" state=absent'

- name: Start vertica
  service: name=verticad enabled=yes
- name: Start vertica_agent
  service: name=vertica_agent enabled=yes
