---
# It is important that the dbadmin users on each node in a cluster can have passwordless ssh access to the other machines
# This is done with a shared private ssh key

# todo first create the dbadmin user and the dbadmin_group

# todo challenges are doing a shared private key that is secure, we can generate one and put it in a variable. Subsequent machines
# will check the variable and their setup. On the next run the first machine will see it has one set and put it into the variable.
# to generate a command such as "ssh-keygen -t rsa -b 2048 -f {{vertica_dbadmin_home}}/.ssh/id_rsa -q -N ''"
# Add the public key to .ssh/authorized_keys

# todo create ~dbadmin/.ssh as the dbadmin user/group mode 700
# Add in a .ssh/config with content="StrictHostKeyChecking no"

# todo create /opt/vertica/config/users/{{vertica_dbadmin_user}} mode 775 group set to root, user to dbadmin
# Create empty file agent.conf to the above dir with mode 664 user/group both root
